### ISSUE TITLE
Adding some sort of analytics?

### ISSUE THREAD

**Issue by anktgasm** [tusharsadhwani/url-shortener#1]
Tried recreating this project with Javascript and here are the [results](https://ankt.me/repo)

Any way to add analytics (gtag or cloudflare) to page redirects, working fine with [404 page](https://github.com/ankityadavhere/url-shortener/blob/main/views/404.hbs) though. But not with redirects!

**Comment by tusharsadhwani** [comment]
Analytics is possible if you add javascript to your redirect, but that would make it pretty slow. I wouldn't want that. So without having a hosted backend, I don't think it'll be easily doable.

Your project should be able to do it though, as it's already getting the redirects from a backend.

**Comment by anktgasm** [comment]
Intresting, i didn't really knew if additional js could be added to redirects
Thanks!
